#include "drumbox.h"

#define CIA2_TB_LO  (*(volatile uint8_t *)0xDD06)
#define CIA2_TB_HI  (*(volatile uint8_t *)0xDD07)
#define CIA2_ICR    (*(volatile uint8_t *)0xDD0D)
#define CIA2_CRB    (*(volatile uint8_t *)0xDD0F)
/* Also need CRA to ensure Timer A stays stopped */
#define CIA2_CRA    (*(volatile uint8_t *)0xDD0E)

/* ── Global state ────────────────────────────────────────────────── */
volatile uint8_t g_cur_step   = 0;
volatile uint8_t g_seq_state  = SEQ_STOPPED;
volatile uint8_t g_tick_flag  = 0;

uint8_t g_tempo      = DEFAULT_TEMPO;
uint8_t g_kit        = KIT_909;
uint8_t g_cur_preset = 0;
uint8_t g_cur_track  = 0;
uint8_t g_cur_col    = 0;
uint8_t g_dual_sid   = 0;

#ifdef NTSC_TIMING
#define CIA_TIMER_VAL  4261u
#else
#define CIA_TIMER_VAL  4105u
#endif

static uint8_t s_tps      = 30;
static uint8_t s_step_acc = 0;

static uint8_t bpm_to_ticks(uint8_t bpm)
{
    uint16_t t;
    if (bpm < 40)  bpm = 40;
    if (bpm > 220) bpm = 220;
    t = 3600u / (uint16_t)bpm;
    if (t < 10) t = 10;
    if (t > 60) t = 60;
    return (uint8_t)t;
}

/* ── seq_init ────────────────────────────────────────────────────── */
void seq_init(void)
{
    g_cur_step  = NUM_STEPS - 1;
    g_seq_state = SEQ_STOPPED;
    g_tick_flag = 0;
    s_step_acc  = 0;
    s_tps       = bpm_to_ticks(g_tempo);

    /* Ensure CIA2 Timer A is stopped (killed NMI source) */
    CIA2_CRA = 0x08;

    /* Stop CIA2 Timer B and clear any pending flags */
    CIA2_CRB = 0x08;

    /* Read CIA2_ICR to clear all pending CIA2 flags */
    (void)CIA2_ICR;

    /* Do NOT write to CIA2_ICR to enable interrupts.
     * We poll only - no NMI/IRQ generated by Timer B. */

    /* Load Timer B latch */
    CIA2_TB_LO = (uint8_t)(CIA_TIMER_VAL & 0xFF);
    CIA2_TB_HI = (uint8_t)(CIA_TIMER_VAL >> 8);

    /* Start Timer B continuous, phi2 clock, force load latch */
    CIA2_CRB = 0x11;   /* force load */
    CIA2_CRB = 0x01;   /* start continuous, phi2, no one-shot */
}

/* ── seq_restore_irq ─────────────────────────────────────────────── */
void seq_restore_irq(void)
{
    CIA2_CRB = 0x08;    /* stop Timer B */
    (void)CIA2_ICR;     /* clear flags */
}

/* ── seq_poll ────────────────────────────────────────────────────── */
/*
 * Call from main loop as fast as possible.
 * Reads CIA2_ICR - bit 1 = Timer B underflow.
 * Reading CIA2_ICR clears CIA2 flags ONLY (never affects CIA1).
 * Zero conflict with KERNAL's CIA1 Timer A IRQ handler.
 */
void seq_poll(void)
{
    uint8_t icr;
    uint8_t track;

    icr = CIA2_ICR;
    if (!(icr & 0x02)) return;   /* bit 1 = Timer B */

    sid_update_sweeps();

    if (g_seq_state != SEQ_PLAYING) return;

    s_step_acc++;
    if (s_step_acc < s_tps) return;
    s_step_acc = 0;

    g_cur_step = (g_cur_step + 1) & (NUM_STEPS - 1);

    for (track = 0; track < NUM_TRACKS; track++) {
        if (g_pattern.steps[track][g_cur_step])
            sid_trigger(track, g_kit);
    }

    g_tick_flag = 1;
}

/* ── Public API ──────────────────────────────────────────────────── */
void seq_start(void)
{
    s_step_acc  = 0;
    g_cur_step  = NUM_STEPS - 1;
    g_tick_flag = 0;
    g_seq_state = SEQ_PLAYING;
}

void seq_stop(void)
{
    g_seq_state = SEQ_STOPPED;
    sid_silence();
}

void seq_set_tempo(uint8_t bpm)
{
    if (bpm < 40)  bpm = 40;
    if (bpm > 220) bpm = 220;
    g_tempo = bpm;
    s_tps   = bpm_to_ticks(bpm);
}

void seq_tick(void) {}